Small Bug Fixes
userscripters/fire-extra-functionality pull request #141
Opened 2023-11-15 15:49 UTC by AppeazeTheCheese

* Removed CSS that was explicitly setting the width of the FIRE popup, making it smaller than it should be.
* Added a wildcard to the end of `https://chat.stackexchange.com/rooms/11540/charcoal-hq` so the script will run even if the URL contains query parameters.

2023-11-17 14:37 UTC, double-beep requested changes
Thanks for your PR! I intentionally chose to run the script only in Charcoal HQ because of all the requests made each time SD sends a message. If more rooms are to be added, then the data the userscript fetches from one room needs to be shared across different tabs, which is - IMO - unnecessary.

2023-11-20 05:57 UTC, AppeazeTheCheese commented
Alright, that makes sense. I'll change it back to what it was with a few additions. I just found myself adding URLs in there more than once, so the last time, I just decided to copy everything from FIRE.

2023-11-21 09:08 UTC, double-beep requested changes

2023-11-21 09:08 UTC, double-beep commented on webpack.config.cjs
> +                     // @match        *://chat.stackexchange.com/rooms/11540/charcoal-hq?*
```suggestion
                     // @match        *://chat.stackexchange.com/rooms/11540/charcoal-hq*
```

Didn't see this earlier, why is `?` needed? It prevents the userscript from running in `https://chat.stackexchange.com/rooms/11540/charcoal-hq`.

2023-11-21 14:20 UTC, AppeazeTheCheese commented
Ah, that is problematic. That's just a typo. I'll fix it really quick.

2023-11-21 17:25 UTC, double-beep approved these changes

2023-11-21 17:27 UTC, merged